schema = 3

[mod]
  [mod."github.com/1password/onepassword-sdk-go"]
    version = "v0.1.0-beta.10"
    hash = "sha256-NzHgJMohV2lIt84bD/zWWQUukPNxNhAuoH/dq9aJwIQ="
  [mod."github.com/extism/go-sdk"]
    version = "v1.2.0"
    hash = "sha256-/ZebHJ/9ec5BAKLBYsHKFCDkwsiycwgJyJdxnY1cvio="
  [mod."github.com/gobwas/glob"]
    version = "v0.2.3"
    hash = "sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc="
  [mod."github.com/tetratelabs/wazero"]
    version = "v1.7.2"
    hash = "sha256-x/fs6ywZ0BLJOKZOfpkOkUPrnexERmKfwsmyKN+KTeg="
